### ISSUE TITLE
申请友链：Velpro's Blog

### ISSUE THREAD

**Issue by tiandankanfeng** [jukebox-org/links#2]
## 申请友链
- 网站名称（必填）: Velpro's Blog

- 网站网址（必填）: https://liangye-xo.xyz

- 网站描述（必填）: Just a CS Programmer

- LOGO URL（可选）: https://liangye-xo.xyz/wp-content/uploads/2022/04/WechatIMG53-300x300.jpeg

- 网站标签（可选）: 博客，社交，生活，分享

**Comment by PipecraftNet** [comment]
感谢光临与关注[聚客盒](https://jukebox.pipecraft.net/)，已添加你的博客到[友情链接](https://jukebox.pipecraft.net/links/)页面里。

我还在我的 [BestXTools](https://discuss-cn.bestxtools.com/) 网站最近注册用户里看到了你，欢迎常来玩。
